name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install .[dev]
        pip install beautifulsoup4 ipython "nbconvert<6.0"
    - name: Validate Sphinx
      run: |
        python scripts/validate_sphinx.py -p "$(pwd)"
    - name: Run sphinx
      run: |
        # warnings treated as errors
        sphinx-build -WT --keep-going sphinx/source sphinx/build
    - name: Validate and parse tutorials
      run: |
        python scripts/parse_tutorials.py -w "$(pwd)"
